### PR TITLE
Setup ember-try Embroider and Ember 3.20 LTS builds

### LINKED ISSUE #173: Setup Embroider CI pipeline
Here is nice guide how to do this: https://medium.com/@kiwiupover/embroider-preparation-14d59edafc0b

### PR DESCRIPTION
**Pull request by raido**
This is blocked by https://github.com/embroider-build/embroider/issues/519

Closes #173.

### CODE REVIEW

**Comment by knownasilya** [comment]
I think if we remove ember-auto-import from deps it would fix it. As far as I know we aren't using auto-import.

**Comment by raido** [comment]
Hmm, I'll try this.

**Comment by raido** [comment]
Things I tried with no avail:

* remove ember-auto-import
* make sure package-lock.json got updated
* rm -r node_modules many times
* regenerated brand new package-lock.json

After all of those things and lot of time, I gave Yarn a try.

* removed package-lock.json
* yarn install to get yarn.lock
* `ember-auto-import` is untouched
* Not believing my eyes: 😮 - embroider build runs just fine both locally and on Travis

WAT

--

I wonder if ember-toggle build will be fine with Yarn as well - https://github.com/embroider-build/embroider/issues/519#issue-700318485

**Comment by knownasilya** [comment]
@raido built ember-toggle without auto-import and 🚀

**Comment by raido** [comment]
It seems it is hoisting issue with NPM vs Yarn - https://github.com/embroider-build/embroider/issues/519#issuecomment-698517572 - if I remove ember-auto-import and ember-cli-fastboot-testing both (which includes ember-auto-import under dependencies) - NPM based build works as well while with Yarn it "just works".

**Comment by knownasilya** [comment]
So not really a solution since an enduser might have auto-import in theirs and might use npm 🤦 But gives us a health check any way, in case anything changes in embroider.

**Comment by raido** [comment]
True. But now we know how users might hit the error on embroider side and hopefully the issue can be fixed for ember-auto-import. 🤞

**Pull request merged**
