### PR TITLE
Moved default config processing to service init()

### PR DESCRIPTION
**Pull request by bgantzler**
Fix for https://github.com/adopted-ember-addons/ember-page-title/issues/142 allow the config to work

### CODE REVIEW

**Comment by bgantzler** [comment]
While I did not change it, I believe defaultReplace should be set to false and not nuill

**Comment by knownasilya** [comment]
Looks like the tests need a look.

**Comment by cah-briangantzler** [comment]
Just an FYI, I am not able to merge this. So since its been approved, someone with permissions would have to do it.

**Comment by knownasilya** [comment]
@cah-briangantzler I can merge once the issue with the tests has been resolved.

**Comment by cah-briangantzler** [comment]
All the tests are passing on released versions of the code. Many tests are failing on beta and canary. Im sorry but Im not sure how to debug install and debug a canary version.

**Comment by cah-briangantzler** [comment]
Ok, during ember 3.15  the following test runs
image

A breakpoint on line 17 shows the following head statement from the dom.
image

A breakpoint on line 19 the DOM contains the same elements. So when line 11 runs, it finds the title and all is fine.

If I installed canary correctly, what I get is at line 17, the same head statement as above, but at line 19 the head looks like the following.

image

I dont know where all the elements went, but line 11 comes back with a null which is why the tests are failing.

What ever the change in beta/canary its beyond the scope of this PR to fix.

**Comment by knownasilya** [comment]
Thanks for digging in. It might be an issue with ember-cli-head it seems.

**Pull request merged**
